# Generated by Django 2.1.4 on 2018-12-14 08:05

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False # <<<< THIS LINE

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Wabpage',
            new_name='Webpage',
        ),
    ]
